"""Сборка сайта: site/src/* -> site/dist/index.html (+ data.json из Git-репозитория данных)."""
import os, glob, shutil
S = os.path.join(os.path.dirname(__file__), "..", "site")
tpl = open(f"{S}/src/template.html", encoding="utf-8").read()
css = open(f"{S}/src/style.css", encoding="utf-8").read()
js = "\n".join(open(p, encoding="utf-8").read() for p in sorted(glob.glob(f"{S}/src/0*.js")))
assert "</script" not in js.lower()
logo = open(f"{S}/src/logo.svg", encoding="utf-8").read().strip()
out = tpl.replace("/*STYLE*/", css).replace("/*SCRIPT*/", js).replace("/*LOGO*/", logo)
os.makedirs(f"{S}/dist", exist_ok=True)
open(f"{S}/dist/index.html", "w", encoding="utf-8").write(out)
shutil.copy(f"{S}/data.json", f"{S}/dist/data.json")
print("ok", len(out))
# Локальный предпросмотр с полным каркасом документа (на claude.ai каркас добавляется при публикации)
open(f"{S}/dist/preview.html", "w", encoding="utf-8").write('<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"></head><body>' + out + "</body></html>")
